FROM ubuntu:14.04

USER root
WORKDIR /root

RUN apt-get update && apt-get install -y \
    \
    lsb-release \
    less man-db \
    openssh-client rsync \
    wget curl ca-certificates \
    pbzip2 \
    nano vim \
    \
    build-essential \
    binutils gcc g++ gfortran \
    python \
    autoconf automake autogen libtool make cmake \
    git-core \
    \
    screen parallel mc \
    \
    dpkg-dev \
    libx11-dev libxpm-dev libxft-dev libxext-dev \
    libpng-dev libjpeg-dev \
    \
    libssl-dev \
    libpcre3-dev \
    libglu1-mesa-dev libglew-dev libftgl-dev \
    libmysqlclient-dev \
    libfftw3-dev \
    libcfitsio3-dev \
    graphviz-dev \
    libavahi-compat-libdnssd-dev \
    python-dev \
    libxml2-dev \
    libgsl0-dev \
    \
    libexpat-dev \
    libxerces-c-dev \
    libxmu-dev \
    \
    python-pip python-setuptools python-dev \
    python-daemon \
    libzmq3-dev \
	\
    libxi-dev \
    \
    && apt-get clean && rm -rf /var/lib/apt/lists/* \
    && locale-gen en_US.UTF-8

RUN pip install --upgrade pip && pip install \
    arrow enum34 luigi subprocess32 \
    jupyter metakernel

# RUN echo "/usr/local/lib" > "/usr/local/lib/python2.7/dist-packages/usr-local-lib.pth"

ENV \
    PATH="/opt/geant4/bin:/opt/clhep/bin:/opt/root/bin:$PATH" \
    LD_LIBRARY_PATH="/opt/geant4/lib:/opt/clhep/lib:/opt/root/lib:/usr/local/lib:$LD_LIBRARY_PATH" \
    MANPATH="/opt/root/man:$MANPATH" \
    PYTHONPATH="/opt/root/lib:$PYTHONPATH" \
    CMAKE_PREFIX_PATH="/opt/root;$CMAKE_PREFIX_PATH" \
    JUPYTER_PATH="/opt/root/etc/notebook:$JUPYTER_PATH" \
    \
    ROOTSYS="/opt/root" \
    \
    G4LEDATA="/opt/geant4/share/Geant4-9.6.4/data/G4EMLOW6.32" \
    G4LEVELGAMMADATA="/opt/geant4/share/Geant4-9.6.4/data/PhotonEvaporation2.3" \
    G4NEUTRONHPDATA="/opt/geant4/share/Geant4-9.6.4/data/G4NDL4.2" \
    G4NEUTRONXSDATA="/opt/geant4/share/Geant4-9.6.4/data/G4NEUTRONXS1.2" \
    G4PIIDATA="/opt/geant4/share/Geant4-9.6.4/data/G4PII1.3" \
    G4RADIOACTIVEDATA="/opt/geant4/share/Geant4-9.6.4/data/RadioactiveDecay3.6" \
    G4REALSURFACEDATA="/opt/geant4/share/Geant4-9.6.4/data/RealSurface1.0" \
    G4SAIDXSDATA="/opt/geant4/share/Geant4-9.6.4/data/G4SAIDDATA1.1" \
    \
    SWMOD_HOSTSPEC=linux-ubuntu-14.04-x86_64-ebd67349

COPY provisioning /root/provisioning
RUN /root/provisioning/install-sw-all.sh

EXPOSE 8082 8888

CMD /bin/bash
